worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost 127.0.0.1 metricore.com.ua www.metricore.com.ua;

        client_max_body_size 100M;

        location /static/ {
            alias T:/planning_front/build/static/;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /docs {
            proxy_pass http://127.0.0.1:8002/docs;
            proxy_set_header Host $host;
        }

        location /openapi.json {
            proxy_pass http://127.0.0.1:8002/openapi.json;
            proxy_set_header Host $host;
        }

        location / {
            root T:/planning_front/build;
            try_files $uri /index.html;
        }
    }
}